"""Document persistence port."""

from typing import Any, Protocol


class DocumentRepositoryPort(Protocol):
    async def list_for_user(self, user_id: str) -> list[Any]: ...

    async def get_for_user(self, document_id: str, user_id: str) -> Any | None: ...

    async def create(self, document: Any) -> Any: ...

    async def add_chunks(self, chunks: list[Any]) -> None: ...

    async def delete(self, document: Any) -> None: ...
